# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60, verbose_name='User_Name')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('password', models.CharField(max_length=10, verbose_name='Password')),
            ],
        ),
    ]
